name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 7.4, 8.0 ]
    name: Tests on PHP ${{ matrix.php }}
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/composer/files
          key: ${{ runner.os }}-cache-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-cache-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: ./vendor/bin/phpunit
